name: Sync Downstream Repo
run-name: "${{ github.event_name == 'workflow_dispatch' && 'Manual Sync to downstream' || format('Sync to downstream repository | {0}', github.event.pull_request.title) }}"

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  sync:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Push to downstream
        env:
          DOWNSTREAM_URL: https://github.com/PMW-robot/downstream-fork.git
        run: |
          git remote add downstream  ${{ env.DOWNSTREAM_URL }}
          git fetch downstream
          git merge downstream/main
          git push downstream